### ISSUE TITLE
no username/password parameters for ES server setting

### ISSUE THREAD

**Issue by osckal** [morningconsult/go-elasticsearch-alerts#33] opened 2019-10-21 03:50 UTC
in the documentation, there is no mention on how to add the username/password for the server url.
adding it inside the url with format http://username:password@esserver:port gives out an error 

> "invalid port ":n" after host. 

need to also allow the username/password to declare as environment variable.

![image](https://user-images.githubusercontent.com/21185820/67175322-3a79a380-f3f8-11e9-9664-6d476b31ac11.png)

**Comment by dbellinghoven** [comment] 2019-10-22 20:23
@osckal I was not able to reproduce the error you mentioned in your original post. It seemed to have no issues with accepting a URL with the format `http://<username>:<password>@esserver:port`. Nevertheless, I added functionality to allow basic auth with HTTP requests in https://github.com/morningconsult/go-elasticsearch-alerts/pull/34. You can set the username and password with the `GO_ELASTICSEARCH_ALERTS_ES_USERNAME` and `GO_ELASTICSEARCH_ALERTS_ES_PASSWORD` environment variables, respectively and it should authenticate your ES requests.

**Comment by osckal** [comment] 2019-10-23 07:40
@dbellinghoven Thanks! looks like it managed to work. however with the authentication now working, I see that it require full access to my elasticsearch (btw I am running es7.1.1)? i have roles set in my cluster; what privilege is needed? right now for testing, it only works properly with superuser role.. if not i will get security exception

**Comment by alexdulin** [comment] 2019-10-23 14:29
I would recommend you read the [the official documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/authorization.html).

Closing this issue as that is outside the scope of this project and the original concern you raised.

**Closed by alexdulin** 2019-10-23 14:29 UTC
